#include "luna/frontend/type/type.h"

#include <gtest/gtest.h>

TEST(TypeTest, ReportsCanonicalProperties) {
    const LunaDataLayout &layout = luna_target_info_default()->data_layout;

    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_I8), "i8");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_I8));
    EXPECT_TRUE(luna_type_kind_is_signed_integer(LUNA_TYPE_I8));
    EXPECT_FALSE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_I8));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_I8, &layout), 8U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_I16), "i16");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_I16));
    EXPECT_TRUE(luna_type_kind_is_signed_integer(LUNA_TYPE_I16));
    EXPECT_FALSE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_I16));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_I16, &layout), 16U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_I32), "i32");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_I32));
    EXPECT_TRUE(luna_type_kind_is_signed_integer(LUNA_TYPE_I32));
    EXPECT_FALSE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_I32));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_I32, &layout), 32U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_I64), "i64");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_I64));
    EXPECT_TRUE(luna_type_kind_is_signed_integer(LUNA_TYPE_I64));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_I64, &layout), 64U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_ISIZE), "isize");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_ISIZE));
    EXPECT_TRUE(luna_type_kind_is_signed_integer(LUNA_TYPE_ISIZE));
    EXPECT_FALSE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_ISIZE));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_ISIZE, &layout), 64U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_U8), "u8");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_U8));
    EXPECT_TRUE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_U8));
    EXPECT_FALSE(luna_type_kind_is_signed_integer(LUNA_TYPE_U8));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_U8, &layout), 8U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_U16), "u16");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_U16));
    EXPECT_TRUE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_U16));
    EXPECT_FALSE(luna_type_kind_is_signed_integer(LUNA_TYPE_U16));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_U16, &layout), 16U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_U32), "u32");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_U32));
    EXPECT_TRUE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_U32));
    EXPECT_FALSE(luna_type_kind_is_signed_integer(LUNA_TYPE_U32));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_U32, &layout), 32U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_U64), "u64");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_U64));
    EXPECT_TRUE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_U64));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_U64, &layout), 64U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_USIZE), "usize");
    EXPECT_TRUE(luna_type_kind_is_integer(LUNA_TYPE_USIZE));
    EXPECT_TRUE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_USIZE));
    EXPECT_FALSE(luna_type_kind_is_signed_integer(LUNA_TYPE_USIZE));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_USIZE, &layout), 64U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_F32), "f32");
    EXPECT_TRUE(luna_type_kind_is_float(LUNA_TYPE_F32));
    EXPECT_FALSE(luna_type_kind_is_integer(LUNA_TYPE_F32));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_F32, &layout), 32U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_F64), "f64");
    EXPECT_TRUE(luna_type_kind_is_float(LUNA_TYPE_F64));
    EXPECT_FALSE(luna_type_kind_is_integer(LUNA_TYPE_F64));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_F64, &layout), 64U);
    EXPECT_FALSE(luna_type_kind_is_integer(LUNA_TYPE_BOOL));
    EXPECT_FALSE(luna_type_kind_is_float(LUNA_TYPE_BOOL));
    EXPECT_FALSE(luna_type_kind_is_signed_integer(LUNA_TYPE_BOOL));
    EXPECT_FALSE(luna_type_kind_is_unsigned_integer(LUNA_TYPE_BOOL));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_BOOL, &layout), 1U);
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_VOID, &layout), 0U);
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_ISIZE, nullptr), 0U);
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_USIZE, nullptr), 0U);
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_NAMED), "named type");
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_STRUCT), "struct");
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_UNION), "union");
    EXPECT_STREQ(luna_type_kind_name(LUNA_TYPE_ENUM), "enum");
    EXPECT_FALSE(luna_type_kind_is_integer(LUNA_TYPE_ENUM));
    EXPECT_FALSE(luna_type_kind_is_float(LUNA_TYPE_ENUM));
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_STRUCT, &layout), 0U);
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_UNION, &layout), 0U);
    EXPECT_EQ(luna_type_kind_bit_width(LUNA_TYPE_ENUM, &layout), 0U);
}
