#ifndef LUNA_TOKEN_H
#define LUNA_TOKEN_H

#include "luna/frontend/source/source.h"

typedef enum LunaTokenKind {
    LUNA_TOKEN_INVALID,
    LUNA_TOKEN_END,

    LUNA_TOKEN_IDENTIFIER,
    LUNA_TOKEN_INTEGER,
    LUNA_TOKEN_FLOAT,
    LUNA_TOKEN_CHARACTER,
    LUNA_TOKEN_STRING,

    LUNA_TOKEN_IMPORT,
    LUNA_TOKEN_MODULE,
    LUNA_TOKEN_EXPORT,
    LUNA_TOKEN_EXTERN,
    LUNA_TOKEN_CONST,
    LUNA_TOKEN_LET,
    LUNA_TOKEN_VAR,
    LUNA_TOKEN_FN,
    LUNA_TOKEN_STRUCT,
    LUNA_TOKEN_UNION,
    LUNA_TOKEN_ENUM,
    LUNA_TOKEN_IF,
    LUNA_TOKEN_ELSE,
    LUNA_TOKEN_SWITCH,
    LUNA_TOKEN_CASE,
    LUNA_TOKEN_DEFAULT,
    LUNA_TOKEN_WHILE,
    LUNA_TOKEN_DO,
    LUNA_TOKEN_FOR,
    LUNA_TOKEN_BREAK,
    LUNA_TOKEN_CONTINUE,
    LUNA_TOKEN_RETURN,
    LUNA_TOKEN_AS,
    LUNA_TOKEN_SIZEOF,
    LUNA_TOKEN_ALIGNOF,
    LUNA_TOKEN_OFFSETOF,
    LUNA_TOKEN_TRUE,
    LUNA_TOKEN_FALSE,
    LUNA_TOKEN_NULL,

    LUNA_TOKEN_BOOL,
    LUNA_TOKEN_I8,
    LUNA_TOKEN_I16,
    LUNA_TOKEN_I32,
    LUNA_TOKEN_I64,
    LUNA_TOKEN_U8,
    LUNA_TOKEN_U16,
    LUNA_TOKEN_U32,
    LUNA_TOKEN_U64,
    LUNA_TOKEN_ISIZE,
    LUNA_TOKEN_USIZE,
    LUNA_TOKEN_F32,
    LUNA_TOKEN_F64,
    LUNA_TOKEN_VOID,

    LUNA_TOKEN_LEFT_PAREN,
    LUNA_TOKEN_RIGHT_PAREN,
    LUNA_TOKEN_LEFT_BRACE,
    LUNA_TOKEN_RIGHT_BRACE,
    LUNA_TOKEN_LEFT_BRACKET,
    LUNA_TOKEN_RIGHT_BRACKET,
    LUNA_TOKEN_COMMA,
    LUNA_TOKEN_DOT,
    LUNA_TOKEN_SEMICOLON,
    LUNA_TOKEN_COLON,
    LUNA_TOKEN_QUESTION,

    LUNA_TOKEN_PLUS,
    LUNA_TOKEN_MINUS,
    LUNA_TOKEN_STAR,
    LUNA_TOKEN_SLASH,
    LUNA_TOKEN_PERCENT,
    LUNA_TOKEN_AMPERSAND,
    LUNA_TOKEN_PIPE,
    LUNA_TOKEN_CARET,
    LUNA_TOKEN_TILDE,
    LUNA_TOKEN_BANG,
    LUNA_TOKEN_EQUAL,
    LUNA_TOKEN_LESS,
    LUNA_TOKEN_GREATER,

    LUNA_TOKEN_ARROW,
    LUNA_TOKEN_PLUS_EQUAL,
    LUNA_TOKEN_MINUS_EQUAL,
    LUNA_TOKEN_STAR_EQUAL,
    LUNA_TOKEN_SLASH_EQUAL,
    LUNA_TOKEN_PERCENT_EQUAL,
    LUNA_TOKEN_AMPERSAND_EQUAL,
    LUNA_TOKEN_PIPE_EQUAL,
    LUNA_TOKEN_CARET_EQUAL,
    LUNA_TOKEN_SHIFT_LEFT,
    LUNA_TOKEN_SHIFT_RIGHT,
    LUNA_TOKEN_SHIFT_LEFT_EQUAL,
    LUNA_TOKEN_SHIFT_RIGHT_EQUAL,
    LUNA_TOKEN_EQUAL_EQUAL,
    LUNA_TOKEN_BANG_EQUAL,
    LUNA_TOKEN_LESS_EQUAL,
    LUNA_TOKEN_GREATER_EQUAL,
    LUNA_TOKEN_LOGICAL_AND,
    LUNA_TOKEN_LOGICAL_OR
} LunaTokenKind;

typedef struct LunaToken {
    LunaTokenKind kind;
    LunaSourceSpan span;
} LunaToken;

const char *luna_token_kind_name(LunaTokenKind kind);

#endif
