#include "luna/token.h"

const char *luna_token_kind_name(LunaTokenKind kind) {
    switch (kind) {
    case LUNA_TOKEN_INVALID:
        return "invalid token";
    case LUNA_TOKEN_END:
        return "end of file";
    case LUNA_TOKEN_IDENTIFIER:
        return "identifier";
    case LUNA_TOKEN_INTEGER:
        return "integer literal";
    case LUNA_TOKEN_FLOAT:
        return "floating-point literal";
    case LUNA_TOKEN_CHARACTER:
        return "character literal";
    case LUNA_TOKEN_STRING:
        return "string literal";
    case LUNA_TOKEN_IMPORT:
        return "'import'";
    case LUNA_TOKEN_MODULE:
        return "'module'";
    case LUNA_TOKEN_EXPORT:
        return "'export'";
    case LUNA_TOKEN_EXTERN:
        return "'extern'";
    case LUNA_TOKEN_CONST:
        return "'const'";
    case LUNA_TOKEN_LET:
        return "'let'";
    case LUNA_TOKEN_VAR:
        return "'var'";
    case LUNA_TOKEN_FN:
        return "'fn'";
    case LUNA_TOKEN_STRUCT:
        return "'struct'";
    case LUNA_TOKEN_UNION:
        return "'union'";
    case LUNA_TOKEN_ENUM:
        return "'enum'";
    case LUNA_TOKEN_IF:
        return "'if'";
    case LUNA_TOKEN_ELSE:
        return "'else'";
    case LUNA_TOKEN_SWITCH:
        return "'switch'";
    case LUNA_TOKEN_CASE:
        return "'case'";
    case LUNA_TOKEN_DEFAULT:
        return "'default'";
    case LUNA_TOKEN_WHILE:
        return "'while'";
    case LUNA_TOKEN_DO:
        return "'do'";
    case LUNA_TOKEN_FOR:
        return "'for'";
    case LUNA_TOKEN_BREAK:
        return "'break'";
    case LUNA_TOKEN_CONTINUE:
        return "'continue'";
    case LUNA_TOKEN_RETURN:
        return "'return'";
    case LUNA_TOKEN_AS:
        return "'as'";
    case LUNA_TOKEN_SIZEOF:
        return "'sizeof'";
    case LUNA_TOKEN_ALIGNOF:
        return "'alignof'";
    case LUNA_TOKEN_OFFSETOF:
        return "'offsetof'";
    case LUNA_TOKEN_TRUE:
        return "'true'";
    case LUNA_TOKEN_FALSE:
        return "'false'";
    case LUNA_TOKEN_NULL:
        return "'null'";
    case LUNA_TOKEN_BOOL:
        return "'bool'";
    case LUNA_TOKEN_I8:
        return "'i8'";
    case LUNA_TOKEN_I16:
        return "'i16'";
    case LUNA_TOKEN_I32:
        return "'i32'";
    case LUNA_TOKEN_I64:
        return "'i64'";
    case LUNA_TOKEN_U8:
        return "'u8'";
    case LUNA_TOKEN_U16:
        return "'u16'";
    case LUNA_TOKEN_U32:
        return "'u32'";
    case LUNA_TOKEN_U64:
        return "'u64'";
    case LUNA_TOKEN_ISIZE:
        return "'isize'";
    case LUNA_TOKEN_USIZE:
        return "'usize'";
    case LUNA_TOKEN_F32:
        return "'f32'";
    case LUNA_TOKEN_F64:
        return "'f64'";
    case LUNA_TOKEN_VOID:
        return "'void'";
    case LUNA_TOKEN_LEFT_PAREN:
        return "'('";
    case LUNA_TOKEN_RIGHT_PAREN:
        return "')'";
    case LUNA_TOKEN_LEFT_BRACE:
        return "'{'";
    case LUNA_TOKEN_RIGHT_BRACE:
        return "'}'";
    case LUNA_TOKEN_LEFT_BRACKET:
        return "'['";
    case LUNA_TOKEN_RIGHT_BRACKET:
        return "']'";
    case LUNA_TOKEN_COMMA:
        return "','";
    case LUNA_TOKEN_DOT:
        return "'.'";
    case LUNA_TOKEN_SEMICOLON:
        return "';'";
    case LUNA_TOKEN_COLON:
        return "':'";
    case LUNA_TOKEN_QUESTION:
        return "'?'";
    case LUNA_TOKEN_PLUS:
        return "'+'";
    case LUNA_TOKEN_MINUS:
        return "'-'";
    case LUNA_TOKEN_STAR:
        return "'*'";
    case LUNA_TOKEN_SLASH:
        return "'/'";
    case LUNA_TOKEN_PERCENT:
        return "'%'";
    case LUNA_TOKEN_AMPERSAND:
        return "'&'";
    case LUNA_TOKEN_PIPE:
        return "'|'";
    case LUNA_TOKEN_CARET:
        return "'^'";
    case LUNA_TOKEN_TILDE:
        return "'~'";
    case LUNA_TOKEN_BANG:
        return "'!'";
    case LUNA_TOKEN_EQUAL:
        return "'='";
    case LUNA_TOKEN_LESS:
        return "'<'";
    case LUNA_TOKEN_GREATER:
        return "'>'";
    case LUNA_TOKEN_ARROW:
        return "'->'";
    case LUNA_TOKEN_PLUS_EQUAL:
        return "'+='";
    case LUNA_TOKEN_MINUS_EQUAL:
        return "'-='";
    case LUNA_TOKEN_STAR_EQUAL:
        return "'*='";
    case LUNA_TOKEN_SLASH_EQUAL:
        return "'/='";
    case LUNA_TOKEN_PERCENT_EQUAL:
        return "'%='";
    case LUNA_TOKEN_AMPERSAND_EQUAL:
        return "'&='";
    case LUNA_TOKEN_PIPE_EQUAL:
        return "'|='";
    case LUNA_TOKEN_CARET_EQUAL:
        return "'^='";
    case LUNA_TOKEN_SHIFT_LEFT:
        return "'<<'";
    case LUNA_TOKEN_SHIFT_RIGHT:
        return "'>>'";
    case LUNA_TOKEN_SHIFT_LEFT_EQUAL:
        return "'<<='";
    case LUNA_TOKEN_SHIFT_RIGHT_EQUAL:
        return "'>>='";
    case LUNA_TOKEN_EQUAL_EQUAL:
        return "'=='";
    case LUNA_TOKEN_BANG_EQUAL:
        return "'!='";
    case LUNA_TOKEN_LESS_EQUAL:
        return "'<='";
    case LUNA_TOKEN_GREATER_EQUAL:
        return "'>='";
    case LUNA_TOKEN_LOGICAL_AND:
        return "'&&'";
    case LUNA_TOKEN_LOGICAL_OR:
        return "'||'";
    }

    return "<unknown token>";
}
